---

- name: Set FAD GLB VS Pool Members REST API endpoint vars ({{ vs_pool_member.server_member_name }}).
  ansible.builtin.set_fact:
    fad_api_endpoint_glb_vs_pool_member:
      "https://{{ ansible_host }}/api/global_load_balance_virtual_server_pool_child_member?\
      vdom={{ fad_vdom }}&pkey={{ vs_pool.name }}&mkey={{ vs_pool_member.id }}"
    fad_glb_vs_pool_member_name: "{{ vs_pool_member.server_member_name + ' of ' + vs_pool.name }}"
    fad_glb_vs_pool_member_existing_data: >
      {{
      (lookup('url',
      'https://%s/api/global_load_balance_virtual_server_pool_child_member?vdom=%s&pkey=%s&mkey=%s'
       % (ansible_host, fad_vdom, vs_pool.name, vs_pool_member.id), validate_certs=false,
       split_lines=false, headers=fad_api_header) | from_json).get('payload')
       }}
    fad_glb_vs_pool_request_body:
      {
        "backup": "{{ vs_pool_member.backup | default('disable') }}",
        "mkey": "{{ vs_pool_member.id | string }}",
        "server": "{{ vs_pool_member.server }}",
        "server-member-name": "{{ vs_pool_member.server_member_name }}",
        "ttl": "{{ vs_pool_member.ttl | default('-1') | string }}",
        "weight": "{{ vs_pool_member.weight | default('1') | string }}"
      }

- name: Print out the GLB VS Pool Members REST API endpoint for {{ fad_glb_vs_pool_member_name }}
  ansible.builtin.debug:
    msg:
      - fad_api_endpoint_glb_vs_pool_member: "{{ fad_api_endpoint_glb_vs_pool_member }}"
      - fad_glb_vs_pool_member_name: "{{ fad_glb_vs_pool_member_name }}"
      - fad_glb_vs_pool_member_existing_data: "{{ fad_glb_vs_pool_member_existing_data }}"
      - fad_glb_vs_pool_request_body: "{{ fad_glb_vs_pool_request_body }}"
  tags:
    - debug

- name: Trying to create new GLB VS Pool Members entry for {{ fad_glb_vs_pool_member_name }}
  ansible.builtin.uri:
    method: POST
    url: "{{ fad_api_endpoint_glb_vs_pool_member }}"
    body_format: "{{ fad_api_uri_params.body_format }}"
    validate_certs: "{{ fad_api_uri_params.validate_certs }}"
    return_content: "{{ fad_api_uri_params.return_content }}"
    status_code: "{{ fad_api_uri_params.status_code }}"
    headers: "{{ fad_api_header }}"
    body: "{{ fad_glb_vs_pool_request_body }}"
  register: fad_glb_vs_pool_member_post_result
  when: fad_glb_vs_pool_member_existing_data.mkey is undefined
  changed_when: "fad_glb_vs_pool_member_post_result.json.payload == 0"
  failed_when: "fad_glb_vs_pool_member_post_result.json.payload != -15 and fad_glb_vs_pool_member_post_result.json.payload != 0"

- name: Update the GLB VS Pool Members entry if entry exist for {{ fad_glb_vs_pool_member_name }}
  ansible.builtin.uri:
    method: PUT
    url: "{{ fad_api_endpoint_glb_vs_pool_member }}"
    body_format: "{{ fad_api_uri_params.body_format }}"
    validate_certs: "{{ fad_api_uri_params.validate_certs }}"
    return_content: "{{ fad_api_uri_params.return_content }}"
    status_code: "{{ fad_api_uri_params.status_code }}"
    headers: "{{ fad_api_header }}"
    body: "{{ fad_glb_vs_pool_request_body }}"
  register: fad_glb_vs_pool_member_put_result
  when: >
    (fad_glb_vs_pool_member_existing_data['mkey'] is defined) and
    (
    fad_glb_vs_pool_member_existing_data['backup'] != vs_pool_member.backup | default('disable') or
    fad_glb_vs_pool_member_existing_data['server'] != vs_pool_member.server or
    fad_glb_vs_pool_member_existing_data['server-member-name'] != vs_pool_member.server_member_name or
    fad_glb_vs_pool_member_existing_data['ttl'] != vs_pool_member.ttl | default('-1') | string or
    fad_glb_vs_pool_member_existing_data['weight'] != vs_pool_member.weight | default('1') | string
    )
  failed_when: "fad_glb_vs_pool_member_put_result.json.payload != -15 and fad_glb_vs_pool_member_put_result.json.payload != 0"
  changed_when: "fad_glb_vs_pool_member_put_result.json.payload == 0"

- name: If the value has changed, print the existing value of the GLB VS Pool Member entry for {{ fad_glb_vs_pool_member_name }}
  ansible.builtin.debug:
    var:
      fad_glb_vs_pool_member_new_data: >
        {{
        (lookup('url',
        'https://%s/api/global_load_balance_virtual_server_pool_child_member?vdom=%s&pkey=%s&mkey=%s'
        % (ansible_host, fad_vdom, vs_pool.name, vs_pool_member.id), validate_certs=false,
        split_lines=false, headers=fad_api_header) | from_json).get('payload')
        }}
  when: >
    (lookup('url',
    'https://%s/api/global_load_balance_virtual_server_pool_child_member?vdom=%s&pkey=%s&mkey=%s'
    % (ansible_host, fad_vdom, vs_pool.name, vs_pool_member.id), validate_certs=false,
    split_lines=false, headers=fad_api_header) | from_json).get('payload') != fad_glb_vs_pool_member_existing_data
  tags:
    - debug
