- name: Create/update data center using role ({{ data_center.name }}).
  ansible.builtin.include_role: ndkprd.fortiadc-glb-data-center
  loop: fad_glb_data_centers
  loop_control:
    loop_var: data_center

- name: Include add GLB server task ({{ data_center.name }}).
  ansible.builtin.include_tasks:  add_glb_servers.yaml
  loop: "{{ data_center.glb_servers }}"
  loop_control:
    loop_var: glb_server
