- name: Create/update GLB VS Pool Members tasks block (({{ server_pool_member.name }})).
  block:

    - name: Set FAD GLB VS Pool Members REST API endpoint vars ({{ server_pool_member.name }}).
      ansible.builtin.set_fact:
        fad_api_endpoint_glb_vs_pools: https://{{ ansible_host }}/api/global_load_balance_virtual_server_pool_member?vdom={{ fad_vdom }}&mkey={{ server_pool_member.name }}
        fad_glb_vs_pool_members_name: "{{ server_pool_member.name }}"

    - name: Print out the GLB VS Pool Members REST API endpoint ({{ fad_glb_vs_pool_members_name }}).
      ansible.builtin.debug:
        msg: "This FAD GLB VS Pool Members REST API endpoint: {{ fad_api_endpoint_glb_vs_pools }}"
      tags:
        - debug

    - name: Get the existing value of GLB VS Pool Members entry ({{ fad_glb_vs_pool_members_name }}).
      ansible.builtin.uri:
        method: GET
        url: "{{ fad_api_endpoint_glb_vs_pools }}"
        body_format: "{{ fad_api_uri_params.body_format }}"
        validate_certs: "{{ fad_api_uri_params.validate_certs }}"
        return_content: "{{ fad_api_uri_params.return_content }}"
        status_code: "{{ fad_api_uri_params.status_code }}"
        headers: "{{ fad_api_header }}"
      register: fad_glb_vs_pool_members_existing_data
      delegate_to: localhost

    - name: Print the existing value of GLB VS Pool Members entry ({{ fad_glb_vs_pool_members_name }}).
      ansible.builtin.debug:
        var: fad_glb_vs_pool_members_existing_data.json.payload
      delegate_to: localhost
      tags:
        - debug

    - name: Write GLB VS Pool Members request body json tmp file ({{ fad_glb_vs_pool_members_name }}).
      ansible.builtin.copy:
        content: |
          {
            "alternate": "",
            "alternate-cmr": "",
            "check-server-status": "{{ server_pool_member.check_server_status }}",
            "check-virtual-server-existent": "{{ server_pool_member.check_virtual_server_existent }}",
            "load-balance-method": "{{ server_pool_member.load_balance_method }}",
            "mkey": "{{ server_pool_member.name }}",
            "preferred": "",
            "preferred-cmr": "",
            "vs_pool_member": "",
            "vs_pool_member_count": ""
          }
        dest: "/tmp/fad_glb_vs_pool_members_{{ server_pool_member.name }}_request_body.json"
        mode: u+rw,g-rw,o-rw
      register: request_body
      delegate_to: localhost
      run_once: true

    - name: Trying to create new GLB VS Pool Members entry ({{ fad_glb_vs_pool_members_name }}).
      ansible.builtin.uri:
        method: POST
        url: "{{ fad_api_endpoint_glb_vs_pools }}"
        body_format: "{{ fad_api_uri_params.body_format }}"
        validate_certs: "{{ fad_api_uri_params.validate_certs }}"
        return_content: "{{ fad_api_uri_params.return_content }}"
        status_code: "{{ fad_api_uri_params.status_code }}"
        headers: "{{ fad_api_header }}"
        body: "{{ lookup('ansible.builtin.file', request_body.dest) }}"
      register: fad_glb_vs_pool_members_post_result
      delegate_to: localhost
      changed_when: "fad_glb_vs_pool_members_post_result.json.payload == 0"
      failed_when: "fad_glb_vs_pool_members_post_result.json.payload != -15 and fad_glb_vs_pool_members_post_result.json.payload != 0"

    - name: Update the GLB VS Pool Members entry if entry exist ({{ fad_glb_vs_pool_members_name }}).
      ansible.builtin.uri:
        method: PUT
        url: "{{ fad_api_endpoint_glb_vs_pools }}"
        body_format: "{{ fad_api_uri_params.body_format }}"
        validate_certs: "{{ fad_api_uri_params.validate_certs }}"
        return_content: "{{ fad_api_uri_params.return_content }}"
        status_code: "{{ fad_api_uri_params.status_code }}"
        headers: "{{ fad_api_header }}"
        body: "{{ lookup('ansible.builtin.file', request_body.dest) }}"
      register: fad_glb_vs_pool_members_put_result
      delegate_to: localhost
      when: "fad_glb_vs_pool_members_post_result.json.payload == -15"
      failed_when: "fad_glb_vs_pool_members_put_result.json.payload != -15 and fad_glb_vs_pool_members_put_result.json.payload != 0"

    - name: Check if the FAD GLB VS Pool Members value has changed ({{ fad_glb_vs_pool_members_name }}).
      ansible.builtin.uri:
        method: GET
        url: "{{ fad_api_endpoint_glb_vs_pools }}"
        body_format: "{{ fad_api_uri_params.body_format }}"
        validate_certs: "{{ fad_api_uri_params.validate_certs }}"
        return_content: "{{ fad_api_uri_params.return_content }}"
        status_code: "{{ fad_api_uri_params.status_code }}"
        headers: "{{ fad_api_header }}"
      register: fad_glb_vs_pool_members_new_data
      changed_when: "fad_glb_vs_pool_members_new_data.json.payload != fad_glb_vs_pool_members_existing_data.json.payload"
      delegate_to: localhost

    - name: Print the existing value of the GLB VS Pool Members entry ({{ fad_glb_vs_pool_members_name }}).
      ansible.builtin.debug:
        var: fad_glb_vs_pool_members_new_data.json
      delegate_to: localhost
      tags:
        - debug

  tags:
    - fad_glb_vsp