- name: Set FAD GLB Servers member REST API endpoint vars ({{ server_member.name }}).
  ansible.builtin.set_fact:
    fad_api_endpoint_server_members: https://{{ ansible_host }}/api/global_load_balance_servers_child_virtual_server_list?vdom={{ fad_vdom }}&pkey={{ glb_server.name }}&mkey={{ server_member.name }}
    fad_glb_servers_member_name: "{{ data_center.name }}/{{ glb_server.name }}/{{ server_member.name }}"

- name: Print out the GLB Servers member REST API endpoint ({{ fad_glb_servers_member_name }}).
  ansible.builtin.debug:
    msg: "This FAD GLB servers member REST API endpoint: {{ fad_api_endpoint_server_members }}"
  tags:
    - debug

- name: Get the existing value of GLB Servers member entry ({{ fad_glb_servers_member_name }}).
  ansible.builtin.uri:
    method: GET
    url: "{{ fad_api_endpoint_server_members }}"
    body_format: "{{ fad_api_uri_params.body_format }}"
    validate_certs: "{{ fad_api_uri_params.validate_certs }}"
    return_content: "{{ fad_api_uri_params.return_content }}"
    status_code: "{{ fad_api_uri_params.status_code }}"
    headers: "{{ fad_api_header }}"
  register: fad_server_members_existing_data
  delegate_to: localhost

- name: Print the existing value of GLB Servers member entry ({{ fad_glb_servers_member_name }}).
  ansible.builtin.debug:
    var: fad_server_members_existing_data.json.payload
  delegate_to: localhost
  tags:
    - debug

- name: Write GLB Servers member request body json tmp file ({{ fad_glb_servers_member_name }}).
  ansible.builtin.copy:
    content: |
      {
        "address-type": "ipv4",
        "gateway": "",
        "health_check_ctrl": "",
        "health_check_inherit": "{{ server_member.health_check_inherit }}",
        "health_check_list": "",
        "health_check_relationship": "OR",
        "ip": "{{ server_member.ip }}",
        "ip6": "::",
        "mkey": "{{ server_member.name }}"
      }
    dest: "/tmp/fad_glb_server_members_{{ server_member.name }}_request_body.json"
    mode: u+rw,g-rw,o-rw
  register: request_body
  delegate_to: localhost
  run_once: true

- name: Trying to create new GLB Servers member entry ({{ fad_glb_servers_member_name }}).
  ansible.builtin.uri:
    method: POST
    url: "{{ fad_api_endpoint_server_members }}"
    body_format: "{{ fad_api_uri_params.body_format }}"
    validate_certs: "{{ fad_api_uri_params.validate_certs }}"
    return_content: "{{ fad_api_uri_params.return_content }}"
    status_code: "{{ fad_api_uri_params.status_code }}"
    headers: "{{ fad_api_header }}"
    body: "{{ lookup('ansible.builtin.file', request_body.dest) }}"
  register: fad_server_members_post_result
  delegate_to: localhost
  changed_when: "fad_server_members_post_result.json.payload == 0"
  failed_when: "fad_server_members_post_result.json.payload != -15 and fad_server_members_post_result.json.payload != 0"

- name: Update the GLB Servers member entry if entry exist ({{ fad_glb_servers_member_name }}).
  ansible.builtin.uri:
    method: PUT
    url: "{{ fad_api_endpoint_server_members }}"
    body_format: "{{ fad_api_uri_params.body_format }}"
    validate_certs: "{{ fad_api_uri_params.validate_certs }}"
    return_content: "{{ fad_api_uri_params.return_content }}"
    status_code: "{{ fad_api_uri_params.status_code }}"
    headers: "{{ fad_api_header }}"
    body: "{{ lookup('ansible.builtin.file', request_body.dest) }}"
  register: fad_server_members_put_result
  delegate_to: localhost
  when: "fad_server_members_post_result.json.payload == -15"
  failed_when: "fad_server_members_put_result.json.payload != -15 and fad_server_members_put_result.json.payload != 0"

- name: Check if the FAD GLB Servers member values has changed ({{ fad_glb_servers_member_name }}).
  ansible.builtin.uri:
    method: GET
    url: "{{ fad_api_endpoint_server_members }}"
    body_format: "{{ fad_api_uri_params.body_format }}"
    validate_certs: "{{ fad_api_uri_params.validate_certs }}"
    return_content: "{{ fad_api_uri_params.return_content }}"
    status_code: "{{ fad_api_uri_params.status_code }}"
    headers: "{{ fad_api_header }}"
  register: fad_server_members_new_data
  changed_when: "fad_server_members_new_data.json.payload != fad_server_members_existing_data.json.payload"
  delegate_to: localhost

- name: Print the existing value of data center entry ({{ fad_glb_servers_member_name }}).
  ansible.builtin.debug:
    var: fad_server_members_new_data.json
  delegate_to: localhost
  tags:
    - debug
