- name: Set GLB DC REST API endpoint ({{ data_center.dc_name }}).
  ansible.builtin.set_fact:
    fad_api_endpoint_glb_dc: https://{{ ansible_host }}/api/global_load_balance_data_center?vdom={{ fad_vdom }}&mkey={{ data_center.dc_name }}

- name: Print out the GLB DC REST API endpoint ({{ data_center.dc_name }}).
  ansible.builtin.debug:
    msg: "This FAD GLB DC REST API endpoint: {{ fad_api_endpoint_glb_dc }}"
  tags:
    - debug

- name: Get the existing value of data center entry ({{ data_center.dc_name }}).
  ansible.builtin.uri:
    method: GET
    url: "{{ fad_api_endpoint_glb_dc }}"
    body_format: "{{ fad_api_uri_params.body_format }}"
    validate_certs: "{{ fad_api_uri_params.validate_certs }}"
    return_content: "{{ fad_api_uri_params.return_content }}"
    status_code: "{{ fad_api_uri_params.status_code }}"
    headers: "{{ fad_api_header }}"
  register: fad_glb_dc_existing_data
  delegate_to: localhost

- name: Print the existing value of data center entry ({{ data_center.dc_name }}).
  ansible.builtin.debug:
    var: fad_glb_dc_existing_data.json.payload
  delegate_to: localhost
  tags:
    - debug

- name: Write request body json tmp file ({{ data_center.dc_name }}).
  ansible.builtin.copy:
    content: |
      {
        "mkey": "{{ data_center.dc_name }}",
        "location": "{{ data_center.location }}"
      }
    dest: "/tmp/fad_glb_dc_{{ data_center.dc_name }}_request_body.json"
    mode: u+rw,g-rw,o-rw
  register: request_body
  delegate_to: localhost
  run_once: true

- name: Trying to create new data center entry ({{ data_center.dc_name }}).
  ansible.builtin.uri:
    method: POST
    url: "{{ fad_api_endpoint_glb_dc }}"
    body_format: "{{ fad_api_uri_params.body_format }}"
    validate_certs: "{{ fad_api_uri_params.validate_certs }}"
    return_content: "{{ fad_api_uri_params.return_content }}"
    status_code: "{{ fad_api_uri_params.status_code }}"
    headers: "{{ fad_api_header }}"
    body: "{{ lookup('ansible.builtin.file', request_body.dest) }}"
  register: fad_glb_dc_post_result
  delegate_to: localhost
  changed_when: "fad_glb_dc_post_result.json.payload == 0"
  failed_when: "fad_glb_dc_post_result.json.payload != -15 and fad_glb_dc_post_result.json.payload != 0"

- name: Update the data center entry if entry exist ({{ data_center.dc_name }}).
  ansible.builtin.uri:
    method: PUT
    url: "{{ fad_api_endpoint_glb_dc }}"
    body_format: "{{ fad_api_uri_params.body_format }}"
    validate_certs: "{{ fad_api_uri_params.validate_certs }}"
    return_content: "{{ fad_api_uri_params.return_content }}"
    status_code: "{{ fad_api_uri_params.status_code }}"
    headers: "{{ fad_api_header }}"
    body: "{{ lookup('ansible.builtin.file', request_body.dest) }}"
  register: fad_glb_dc_put_result
  delegate_to: localhost
  when: "fad_glb_dc_post_result.json == -15"
  failed_when: "fad_glb_dc_put_result.json.payload != -15 and fad_glb_dc_put_result.json.payload != 0"

- name: Check if the data center value has changed ({{ data_center.dc_name }}).
  ansible.builtin.uri:
    method: GET
    url: "{{ fad_api_endpoint_glb_dc }}"
    body_format: "{{ fad_api_uri_params.body_format }}"
    validate_certs: "{{ fad_api_uri_params.validate_certs }}"
    return_content: "{{ fad_api_uri_params.return_content }}"
    status_code: "{{ fad_api_uri_params.status_code }}"
    headers: "{{ fad_api_header }}"
  register: fad_glb_dc_new_data
  changed_when: "fad_glb_dc_new_data.json.payload != fad_glb_dc_existing_data.json.payload"
  delegate_to: localhost

- name: Print the existing value of data center entry ({{ data_center.dc_name }}).
  ansible.builtin.debug:
    var: fad_glb_dc_new_data.json
  delegate_to: localhost
  tags:
    - debug

- name: Include add GLB server task ({{ data_center.dc_name }}).
  ansible.builtin.include_tasks:  add_glb_servers.yaml
  loop: "{{ data_center.glb_servers }}"
  loop_control:
    loop_var: glb_server