- name: Set fad_glb_servers REST API endpoint var ({{ glb_server.name }}).
  ansible.builtin.set_fact:
    fad_api_endpoint_glb_servers: https://{{ ansible_host }}/api/global_load_balance_servers?vdom={{ fad_vdom }}&mkey={{ glb_server.name }}

- name: Print out the GLB servers REST API endpoint ({{ glb_server.name }}).
  ansible.builtin.debug:
    msg: "This FAD GLB servers REST API endpoint: {{ fad_api_endpoint_glb_servers }}"
  tags:
    - debug

- name: Get the existing value of GLB servers entry ({{ glb_server.name }}).
  ansible.builtin.uri:
    method: GET
    url: "{{ fad_api_endpoint_glb_servers }}"
    body_format: "{{ fad_api_uri_params.body_format }}"
    validate_certs: "{{ fad_api_uri_params.validate_certs }}"
    return_content: "{{ fad_api_uri_params.return_content }}"
    status_code: "{{ fad_api_uri_params.status_code }}"
    headers: "{{ fad_api_header }}"
  register: fad_glb_servers_existing_data
  delegate_to: localhost

- name: Print the existing value of data center entry ({{ glb_server.name }}).
  ansible.builtin.debug:
    var: fad_glb_servers_existing_data.json.payload
  delegate_to: localhost
  tags:
    - debug