---

- name: Create/update data center using role ({{ data_center.name }}).
  ansible.builtin.include_role: ndkprd.fortiadc-glb-data-center
  loop: "{{ fad_glb_data_centers }}"
  loop_control:
    loop_var: data_center

- name: Create/update GLB Data Centers, Servers, and Servers Member.
  ansible.builtin.include_tasks: add_glb_data_center.yaml
  loop: "{{ fad_glb_data_centers }}"
  loop_control:
    loop_var: data_center
