---

- name: Include task to include role to create/update GLB Data Centers, Servers, and Servers Members using role.
  ansible.builtin.include_tasks: include_role.yaml
  tags:
    - preparation

- name: Include task to create/update GLB VSP.
  ansible.builtin.include_tasks: add_glb_vs_pools.yaml
  loop: "{{ fad_glb_vs_pools }}"
  loop_control:
    loop_var: server_pool
