---

- name: Update/create FortiADC GLB Data Centers resources.
  hosts: all
  become: false
  gather_facts: false
  connection: local
  vars:
     # for testing-purpose only, to delete the created resources after. change to 'false' if you want the resource to stay.
    do_cleanup: true

  roles:
    # uncomment below to test against ansible-galaxy
    - ndkprd.fortiadc-glb-vs-pools
    # uncomment below to test against local (note: this will not pass ansible-lint)
    # - ../../ansible-role-fortiadc-glb-vs-pools

  # clean-up tasks if you need to delete the resources you just create.
  tasks:
    - name: Clean up the created VS Pools resources.
      ansible.builtin.uri:
        method: DELETE
        url: "https://{{ ansible_host }}/api/global_load_balance_virtual_server_pool?vdom={{ fad_vdom }}&mkey={{ item.name }}"
        body_format: "{{ fad_api_uri_params.body_format }}"
        validate_certs: "{{ fad_api_uri_params.validate_certs }}"
        return_content: "{{ fad_api_uri_params.return_content }}"
        status_code: "{{ fad_api_uri_params.status_code }}"
        headers: "{{ fad_api_header }}"
      register: fad_glb_dc_existing_data
      when: do_cleanup == 'true' | bool | default('false')
      loop: "{{ fad_glb_vs_pools }}"
      loop_control:
        label: "{{ item.name }}"
      tags:
        - cleanup

    - name: Clean up the created Servers resources.
      ansible.builtin.uri:
        method: DELETE
        url: "https://{{ ansible_host }}/api/global_load_balance_servers?vdom={{ fad_vdom }}&mkey={{ item.name }}"
        body_format: "{{ fad_api_uri_params.body_format }}"
        validate_certs: "{{ fad_api_uri_params.validate_certs }}"
        return_content: "{{ fad_api_uri_params.return_content }}"
        status_code: "{{ fad_api_uri_params.status_code }}"
        headers: "{{ fad_api_header }}"
      register: fad_glb_dc_existing_data
      when: do_cleanup == 'true' | bool | default('false')
      loop: "{{ fad_glb_servers }}"
      loop_control:
        label: "{{ item.name }}"
      tags:
        - cleanup

    - name: Clean up the created Data Centers resources.
      ansible.builtin.uri:
        method: DELETE
        url: "https://{{ ansible_host }}/api/global_load_balance_data_center?vdom={{ fad_vdom }}&mkey={{ item.name }}"
        body_format: "{{ fad_api_uri_params.body_format }}"
        validate_certs: "{{ fad_api_uri_params.validate_certs }}"
        return_content: "{{ fad_api_uri_params.return_content }}"
        status_code: "{{ fad_api_uri_params.status_code }}"
        headers: "{{ fad_api_header }}"
      register: fad_glb_dc_existing_data
      when: do_cleanup == 'true' | bool | default('false')
      loop: "{{ fad_glb_data_centers }}"
      loop_control:
        label: "{{ item.name }}"
      tags:
        - cleanup
